# Generated by Django 6.0.4 on 2026-04-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contragent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
                ('ogrn', models.CharField(max_length=15, verbose_name='ОГРН')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('short_name', models.TextField(verbose_name='Краткое название')),
                ('full_name', models.TextField(verbose_name='Полное название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('position', models.CharField(max_length=64, verbose_name='Должность')),
                ('full_fio', models.CharField(max_length=128, verbose_name='ФИО')),
                ('initials_fio', models.CharField(editable=False, max_length=128, verbose_name='Фамилия и инициалы')),
            ],
        ),
    ]
