# Generated by Django 6.0.4 on 2026-04-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль')),
                ('role', models.CharField(choices=[('guest', 'Гость'), ('secret', 'Секретарь'), ('undir', 'Заместитель директора'), ('dir', 'Директор')], default='guest', max_length=20, verbose_name='Должность')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('work_phone', models.CharField(max_length=20, verbose_name='Рабочий телефон')),
                ('personal_phone', models.CharField(blank=True, max_length=20, verbose_name='Личный телефон')),
            ],
        ),
    ]
