# Generated by Django 6.0.5 on 2026-05-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rent', 'Аренда помещения'), ('salary', 'Зарплата сотрудников'), ('utilities', 'Коммунальные услуги'), ('marketing', 'Маркетинг и реклама'), ('supplies', 'Закупка сырья/товаров'), ('transport', 'Транспорт и логистика')], max_length=50, verbose_name='Тип издержки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма (руб.)')),
                ('date', models.DateField(verbose_name='Дата учёта')),
            ],
        ),
    ]
