# Generated by Django 6.0.5 on 2026-05-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, verbose_name='Номер сотрудника')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма начисления')),
            ],
        ),
    ]
