# Generated by Django 6.0.5 on 2026-05-20 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка автомобиля')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Государственный номер')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('fuel_rate', models.FloatField(verbose_name='Норма расхода (л/км)')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО водителя')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='probeg.car', verbose_name='Текущая машина')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='Время выезда')),
                ('arrival_time', models.DateTimeField(verbose_name='Время заезда')),
                ('start_mileage', models.FloatField(verbose_name='Начальный километраж')),
                ('end_mileage', models.FloatField(verbose_name='Конечный километраж')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='probeg.car', verbose_name='Автомобиль')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='probeg.driver', verbose_name='Водитель')),
            ],
        ),
    ]
