# Generated by Django 6.0.5 on 2026-05-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probeg', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='car',
        ),
        migrations.AddField(
            model_name='driver',
            name='cars',
            field=models.ManyToManyField(blank=True, to='probeg.car', verbose_name='Машины'),
        ),
    ]
